export const resList = [
  {
    id: 0,
    name: "Spice Villa",
    cuisine: ["North Indian", "Chinese"],
    avgRating: 3,
    costForTwo: 400,
    deliveryTime: "30-40 mins",
    imageId: "sample",
  },
  {
    id: 1,
    name: "Burger Nation",
    cuisine: ["American", "Fast Food"],
    avgRating: 4.2,
    costForTwo: 300,
    deliveryTime: "20-30 mins",
    imageId: "food/burger",
  },
  {
    id: 2,
    name: "Tandoori Nights",
    cuisine: ["Mughlai", "Barbecue"],
    avgRating: 4.7,
    costForTwo: 600,
    deliveryTime: "40-50 mins",
    imageId: "food/chicken",
  },
  {
    id: 3,
    name: "Green Leaf",
    cuisine: ["Vegan", "Salads"],
    avgRating: 4.3,
    costForTwo: 350,
    deliveryTime: "25-35 mins",
    imageId: "food/salad",
  },
  {
    id: 4,
    name: "Pizza Mania",
    cuisine: ["Italian", "Pizza"],
    avgRating: 4.1,
    costForTwo: 500,
    deliveryTime: "30-45 mins",
    imageId: "food/pizza",
  },
  {
    id: 5,
    name: "Sushi Central",
    cuisine: ["Japanese"],
    avgRating: 4.6,
    costForTwo: 700,
    deliveryTime: "45-55 mins",
    imageId: "food/sushi",
  },
  {
    id: 6,
    name: "The Dosa House",
    cuisine: ["South Indian"],
    avgRating: 4.4,
    costForTwo: 250,
    deliveryTime: "20-25 mins",
    imageId: "food/dosa",
  },
  {
    id: 7,
    name: "Wrap & Roll",
    cuisine: ["Fast Food", "Snacks"],
    avgRating: 4.0,
    costForTwo: 200,
    deliveryTime: "15-20 mins",
    imageId: "food/wrap",
  },
  {
    id: 8,
    name: "Biryani Express",
    cuisine: ["Hyderabadi", "Biryani"],
    avgRating: 4.8,
    costForTwo: 450,
    deliveryTime: "35-45 mins",
    imageId: "food/biryani",
  },
  {
    id: 9,
    name: "Chaat Junction",
    cuisine: ["Street Food", "Chaat"],
    avgRating: 4.1,
    costForTwo: 180,
    deliveryTime: "10-15 mins",
    imageId: "food/chat",
  },
];
